apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
spec:
  template:
    spec:
      containers:
        - name: flagger
          args:
            - -mesh-provider=kubernetes
            - -metrics-server=http://flagger-prometheus:9090
            - -slack-user=flagger
            - -slack-channel=flux-flagger
            - -slack-url=https://hooks.slack.com/services/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
