apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
spec:
  template:
    spec:
      containers:
        - name: flagger
          args:
            - -mesh-provider=kubernetes
            - -metrics-server=http://flagger-prometheus:9090
            - -slack-user=flagger
            - -slack-channel=flux-flagger
            - -slack-url=$(FLAGGER_SLACK_WEBHOOK)
          envFrom:
            - secretRef:
                name: flagger-secrets
